// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekkvpydcajpyzmcohssc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVra3ZweWRjYWpweXptY29oc3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODU5NTUsImV4cCI6MjA3Mjg2MTk1NX0.NSJrSMoegsQsNRza05jYQlpMx81dcXISWlvKpwAAMT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});